import Link from "next/link";

export default function Home() { return <>
<section className="hero"><p className="eyebrow">CONFIDENTIAL PRIZE SAVINGS · ETHEREUM SEPOLIA</p><h1>SAVE WITHOUT<br/>BEING SEEN.</h1><p className="lede">Your savings remain private. Your wins remain private. The draw remains publicly verifiable — without publishing the pool's financial state.</p><div className="actions"><Link className="button primary" href="/pool">ENTER THE POOL</Link><Link className="button" href="/verify">SEE THE LIVE PROOF</Link></div></section>
<section className="metrics"><div><span>PUBLIC CAPACITY</span><strong>1,073.74 cUSDT</strong><small>Fixed 2³⁰ draw domain</small></div><div><span>TOTAL SAVED</span><strong className="encrypted">████████</strong><small>Encrypted</small></div><div><span>CURRENT PRIZE</span><strong className="encrypted">████████</strong><small>Encrypted</small></div><div><span>DRAW #1</span><strong>FINALIZED</strong><small>Verified on Sepolia</small></div></section>
<section className="split"><div><p className="eyebrow">THE DARK CAPACITY DRAW</p><h2>VERIFY EVERYTHING.<br/>WITHOUT SEEING EVERYTHING.</h2></div><div className="copy"><p>Eclipse draws against a fixed public capacity instead of public TVL. Saver balances form encrypted cumulative ranges. Zama FHE generates the random position and evaluates the winner directly over ciphertexts.</p><p>If the encrypted point lands in unused capacity, <em>The Shadow</em> takes the outcome and the prize rolls forward. Principal never becomes prize liquidity.</p></div></section>
<section className="capacity"><div className="axis"><span>0</span><span>ENCRYPTED SAVER SPACE</span><span>2³⁰</span></div><div className="bar"><i/><i/><i/><b>THE SHADOW</b></div><p>Conceptual only. Block widths do not represent live balances or pool utilization.</p></section>
<section className="manifesto"><span>NO PUBLIC TVL.</span><span>NO PUBLIC ODDS.</span><span>NO PUBLIC WINNER.</span></section>
</>; }
