"use client";

import { BrowserProvider, Contract, formatUnits, parseUnits } from "ethers";
import { CONTRACTS, CUSDT_ABI, DRAW_ABI, PUBLIC_SEPOLIA_RPC, SEPOLIA_CHAIN_HEX, SEPOLIA_CHAIN_ID, TOKEN_DECIMALS, USDT_ABI, VAULT_ABI } from "./contracts";

type EthereumProvider = { request(args: { method: string; params?: unknown[] | object }): Promise<unknown>; on?: (event: string, cb: (...args: unknown[]) => void) => void; removeListener?: (event: string, cb: (...args: unknown[]) => void) => void; providers?: EthereumProvider[]; isMetaMask?: boolean; };
type Eip6963Detail = { info: { rdns?: string; name?: string }; provider: EthereumProvider };
type HexHandle = `0x${string}`;
type RelayerSdk = typeof import("@zama-fhe/relayer-sdk/web");
type FheInstance = Awaited<ReturnType<RelayerSdk["createInstance"]>>;
declare global { interface Window { ethereum?: EthereumProvider } }
let fhePromise: Promise<FheInstance> | undefined; let preferredProvider: EthereumProvider | undefined;

function injectedFallback() { if (typeof window === "undefined" || !window.ethereum) throw new Error("Install a browser wallet such as MetaMask to continue."); const injected=window.ethereum; if(Array.isArray(injected.providers)&&injected.providers.length)return injected.providers.find(p=>p.isMetaMask)??injected.providers[0]; return injected; }
export async function discoverWalletProvider(){if(preferredProvider)return preferredProvider;if(typeof window==="undefined")throw new Error("No browser wallet available.");const discovered:Eip6963Detail[]=[];const onAnnounce=(event:Event)=>{const detail=(event as CustomEvent<Eip6963Detail>).detail;if(detail?.provider)discovered.push(detail);};window.addEventListener("eip6963:announceProvider",onAnnounce as EventListener);window.dispatchEvent(new Event("eip6963:requestProvider"));await new Promise(r=>setTimeout(r,150));window.removeEventListener("eip6963:announceProvider",onAnnounce as EventListener);const metamask=discovered.find(e=>e.info?.rdns==="io.metamask")??discovered.find(e=>/metamask/i.test(e.info?.name??""));preferredProvider=metamask?.provider??discovered[0]?.provider??injectedFallback();return preferredProvider;}
export function ethereum(){return preferredProvider??injectedFallback();}
export async function connectWallet(){const provider=await discoverWalletProvider();const accounts=await provider.request({method:"eth_requestAccounts"}) as string[];if(!Array.isArray(accounts)||!accounts[0])throw new Error("Wallet returned no account.");return accounts[0];}
export async function browserProvider(){return new BrowserProvider(await discoverWalletProvider() as never);}
export async function signer(){return(await browserProvider()).getSigner();}
export async function account(){return(await signer()).getAddress();}
async function requireSepolia(){const network=await(await browserProvider()).getNetwork();if(Number(network.chainId)!==SEPOLIA_CHAIN_ID)throw new Error("Network mismatch: switch to Ethereum Sepolia.");}
function amount64(amount:string){if(!/^\d+(\.\d{1,6})?$/.test(amount)||Number(amount)<=0)throw new Error("Enter a valid positive amount with up to 6 decimals.");const value=parseUnits(amount,TOKEN_DECIMALS);if(value>18_446_744_073_709_551_615n)throw new Error("Amount exceeds encrypted uint64 range.");return value;}
export async function switchToSepolia(){const provider=await discoverWalletProvider();try{await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:SEPOLIA_CHAIN_HEX}]});}catch(error:unknown){const code=typeof error==="object"&&error&&"code" in error?(error as {code?:number}).code:undefined;if(code!==4902)throw error;await provider.request({method:"wallet_addEthereumChain",params:[{chainId:SEPOLIA_CHAIN_HEX,chainName:"Ethereum Sepolia",nativeCurrency:{name:"Sepolia ETH",symbol:"ETH",decimals:18},rpcUrls:[PUBLIC_SEPOLIA_RPC],blockExplorerUrls:["https://sepolia.etherscan.io"]}]});}}
export async function fhe(){if(!fhePromise){fhePromise=(async()=>{const sdk=await import("@zama-fhe/relayer-sdk/web");const initialized=await sdk.initSDK();if(!initialized)throw new Error("Zama FHE SDK failed to initialize.");return sdk.createInstance({...sdk.SepoliaConfig,network:PUBLIC_SEPOLIA_RPC});})().catch(error=>{fhePromise=undefined;throw error;});}return fhePromise;}
export async function encrypt64(contractAddress:string,userAddress:string,value:bigint){const instance=await fhe();return instance.createEncryptedInput(contractAddress,userAddress).add64(value).encrypt();}
async function decryptHandles(userAddress:string,entries:{handle:HexHandle;contractAddress:string}[]){const instance=await fhe();const wallet=await signer();const keypair=instance.generateKeypair();const contracts=[...new Set(entries.map(e=>e.contractAddress))];const startTime=Math.floor(Date.now()/1000);const days=10;const typed=instance.createEIP712(keypair.publicKey,contracts,startTime,days);const types={UserDecryptRequestVerification:[...typed.types.UserDecryptRequestVerification]};const signature=await wallet.signTypedData(typed.domain,types,typed.message);return instance.userDecrypt(entries,keypair.privateKey,keypair.publicKey,signature.slice(2),contracts,userAddress,startTime,days);}
export async function unlockPrincipal(userAddress:string){await requireSepolia();const provider=await browserProvider();const vault=new Contract(CONTRACTS.vault,VAULT_ABI,provider);const handle=String(await vault.principalOf(userAddress)) as HexHandle;if(/^0x0{64}$/i.test(handle))return{raw:0n,formatted:"0.0"};const values=await decryptHandles(userAddress,[{handle,contractAddress:CONTRACTS.vault}]);const raw=BigInt(values[handle] as bigint|number|string);return{raw,formatted:formatUnits(raw,TOKEN_DECIMALS)};}
export async function depositCusdt(amount:string,onStep?:(step:string)=>void){await requireSepolia();const wallet=await signer();const user=await wallet.getAddress();onStep?.("ENCRYPTING AMOUNT");const encrypted=await encrypt64(CONTRACTS.cUsdt,user,amount64(amount));onStep?.("WAITING FOR WALLET");const token=new Contract(CONTRACTS.cUsdt,CUSDT_ABI,wallet);const tx=await token.confidentialTransferAndCall(CONTRACTS.vault,encrypted.handles[0],encrypted.inputProof,"0x");onStep?.("SUBMITTING TO SEPOLIA");await tx.wait();onStep?.("DEPOSIT CONFIRMED — UNLOCK BALANCE TO VERIFY PRIVATE ACCEPTANCE");return tx.hash as string;}
export async function withdrawPrincipal(amount:string,onStep?:(step:string)=>void){await requireSepolia();const wallet=await signer();const user=await wallet.getAddress();const provider=await browserProvider();const vaultRead=new Contract(CONTRACTS.vault,VAULT_ABI,provider);if(await vaultRead.withdrawalsLocked())throw new Error("A draw is being finalized. Withdrawals reopen after finalization.");onStep?.("ENCRYPTING REQUEST");const encrypted=await encrypt64(CONTRACTS.vault,user,amount64(amount));const vault=new Contract(CONTRACTS.vault,VAULT_ABI,wallet);onStep?.("SUBMITTING");const tx=await vault.withdraw(encrypted.handles[0],encrypted.inputProof);await tx.wait();onStep?.("WITHDRAWAL CONFIRMED");return tx.hash as string;}
export async function mintTestUsdt(amount:string){await requireSepolia();const wallet=await signer();const user=await wallet.getAddress();const token=new Contract(CONTRACTS.usdt,USDT_ABI,wallet);const tx=await token.mint(user,amount64(amount));await tx.wait();return tx.hash as string;}
export async function wrapTestUsdt(amount:string){await requireSepolia();const wallet=await signer();const user=await wallet.getAddress();const value=amount64(amount);const underlying=new Contract(CONTRACTS.usdt,USDT_ABI,wallet);const approve=await underlying.approve(CONTRACTS.cUsdt,value);await approve.wait();const token=new Contract(CONTRACTS.cUsdt,CUSDT_ABI,wallet);const tx=await token.wrap(user,value);await tx.wait();return tx.hash as string;}
function asBool(value:unknown){if(typeof value==="boolean")return value;if(typeof value==="bigint")return value!==0n;if(typeof value==="number")return value!==0;if(typeof value==="string")return value==="true"||value==="1";return false;}
export async function currentDraw(){const draw=new Contract(CONTRACTS.draw,DRAW_ABI,await browserProvider());return{id:BigInt(await draw.currentDrawId()),state:Number(await draw.state()),cursor:BigInt(await draw.cursor())};}
export async function runNextDraw(onStep?:(step:string)=>void){await requireSepolia();const wallet=await signer();const draw=new Contract(CONTRACTS.draw,DRAW_ABI,wallet);const vault=new Contract(CONTRACTS.vault,VAULT_ABI,await browserProvider());let state=Number(await draw.state());if(state===3){onStep?.("OPENING NEXT DRAW");const tx=await draw.openNextDraw();await tx.wait();state=0;}if(state===0){onStep?.("LOCKING PRIZE + CREATING ENCRYPTED RANDOMNESS");const tx=await draw.startDraw();await tx.wait();state=1;}if(state===1){onStep?.("BEGINNING ENCRYPTED PROCESSING");const tx=await draw.beginProcessing();await tx.wait();state=2;}if(state===2){const total=BigInt(await vault.participantCount());let cursor=BigInt(await draw.cursor());while(cursor<total){const remaining=total-cursor;const count=remaining>16n?16n:remaining;onStep?.(`PROCESSING ENCRYPTED BALANCES ${cursor+1n}–${cursor+count} OF ${total}`);const tx=await draw.processDrawBatch(count);await tx.wait();cursor=BigInt(await draw.cursor());}onStep?.("FINALIZING ENCRYPTED WINNER / SHADOW OUTCOME");const tx=await draw.finalizeDraw();await tx.wait();}const id=BigInt(await draw.currentDrawId());onStep?.(`DRAW #${id} FINALIZED`);return id;}
export async function unlockDrawResult(userAddress:string,drawId?:bigint){await requireSepolia();const wallet=await signer();const draw=new Contract(CONTRACTS.draw,DRAW_ABI,wallet);const id=drawId??BigInt(await draw.currentDrawId());if(!(await draw.finalized(id)))throw new Error(`Draw #${id} is not finalized yet.`);const[wonRaw,prizeRaw]=await draw.encryptedResultOf(id,userAddress);const wonHandle=String(wonRaw) as HexHandle;const prizeHandle=String(prizeRaw) as HexHandle;if(BigInt(wonHandle)===0n||BigInt(prizeHandle)===0n)throw new Error(`This wallet did not participate in Draw #${id}.`);const auth=await draw.authorizeMyResult(id);await auth.wait();const values=await decryptHandles(userAddress,[{handle:wonHandle,contractAddress:CONTRACTS.draw},{handle:prizeHandle,contractAddress:CONTRACTS.draw}]);return{id,won:asBool(values[wonHandle]),prize:formatUnits(BigInt(values[prizeHandle] as bigint|number|string),TOKEN_DECIMALS)};}
export async function claimDrawPrize(drawId?:bigint){await requireSepolia();const wallet=await signer();const user=await wallet.getAddress();const draw=new Contract(CONTRACTS.draw,DRAW_ABI,wallet);const id=drawId??BigInt(await draw.currentDrawId());if(await draw.claimed(id,user))throw new Error("This draw result has already been claimed.");const tx=await draw.claimPrize(id);await tx.wait();return tx.hash as string;}
export function friendlyError(error:unknown){const code=typeof error==="object"&&error&&"code" in error?String((error as {code?:unknown}).code??""):"";const message=error instanceof Error?error.message:String(error);if(/user rejected|denied/i.test(message)||code==="4001")return"The wallet request was cancelled.";if(/already processing|request.*pending|pending request/i.test(message)||code==="-32002")return"A wallet request is already open. Finish or cancel it in MetaMask, then try again.";if(/install a browser wallet|no provider|ethereum is not defined/i.test(message))return"No compatible browser wallet was detected. Install or unlock MetaMask and try again.";if(/network mismatch|switch to ethereum sepolia/i.test(message))return"Switch to Ethereum Sepolia and try again.";if(/valid positive amount|uint64 range/i.test(message))return message;if(/fhe sdk failed|initsdk|wasm/i.test(message))return`Zama encryption failed to initialize: ${message}`;if(/already.*claimed/i.test(message))return"This draw result has already been claimed.";if(/insufficient funds/i.test(message))return"You need enough test-token balance and Sepolia ETH for gas.";if(/draw is being finalized|withdrawals.*reopen/i.test(message))return"A draw is being finalized. Withdrawals reopen after finalization.";if(/not finalized/i.test(message)||/participate/i.test(message))return message;return`Request failed${code?` (${code})`:""}${message&&message!=="[object Object]"?`: ${message.slice(0,220)}`:". Please try again."}`;}
